services:

  apache:
    build:
      dockerfile: compose/Dockerfile
      args:
        - DOC=${DOC}
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      mysql:
        condition: service_healthy
        restart: true
      rabbitmq:
        condition: service_healthy
    environment:
      DOC: ${DOC}
      MYSQL_HOST: mysql
      RABBITMQ_HOST: rabbitmq
      GIT_COMMIT_NAME: ${GIT_COMMIT_NAME:-}
      GIT_COMMIT_EMAIL: ${GIT_COMMIT_EMAIL:-}
      LETS_ENCRYPT_DOMAIN: ${LETS_ENCRYPT_DOMAIN:-}
      EMAIL_SENDER_DOMAIN: ${EMAIL_SENDER_DOMAIN:-}
    volumes:
      - ./:${DOC}/
      - mysql_server_data:/var/lib/mysql
      - mysql_client_binaries:/usr/bin/mysql_client_binaries
      - letsencrypt:/etc/letsencrypt
      - opendkim:/etc/opendkim
      - ./compose/opendkim.conf:/etc/opendkim.conf
      - ./compose/php.system.ini:/etc/php/8.3/apache2/conf.d/php.system.ini
      - ./compose/php.system.ini:/etc/php/8.3/cli/conf.d/php.system.ini

  mysql:
    image: mysql:8.0.36-debian
    command:
      --default-authentication-plugin=mysql_native_password
      --sql_mode=ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION,STRICT_TRANS_TABLES
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
      --innodb_buffer_pool_size=4294967296
      --wait_timeout=31536000
      --max_execution_time=20000
      --slow_query_log=ON
    ports:
      - "3306:3306"
    environment:
      TZ: Europe/Berlin
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-custom}
      MYSQL_USER: ${MYSQL_USER:-custom}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-custom}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-custom}
      MYSQL_DUMP: ${MYSQL_DUMP}
      GH_TOKEN: ${GH_TOKEN}
    volumes:
      - ./compose/mysql/docker-entrypoint.sh:/usr/local/bin/custom-entrypoint.sh:ro
      - ./sql/:/docker-entrypoint-initdb.d/custom/
      - ./.git/config:/docker-entrypoint-initdb.d/.gitconfig:ro
      - mysql_server_data:/var/lib/mysql
      - mysql_client_binaries:/usr/bin/volumed
    healthcheck:
      test: mysqladmin ping && [ -f /var/lib/mysql/init.done ]
      start_period: 7m
      interval: 5s
    entrypoint: /usr/local/bin/custom-entrypoint.sh

  rabbitmq:
    image: rabbitmq:3.10-management-alpine
    ports:
      - "15672:15672"
    volumes:
      - ./compose/rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - ./compose/rabbitmq/enabled_plugins:/etc/rabbitmq/enabled_plugins
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      timeout: 20s
      retries: 10
    command: rabbitmq-server

volumes:
  mysql_server_data:
  mysql_client_binaries:
  letsencrypt:
  opendkim:
